### ISSUE TITLE
移动端页面宽度溢出

### ISSUE THREAD

**Issue by hellflame** [idbord/Luffy#1]
![issue1](http://7xp8li.com1.z0.glb.clouddn.com/luffy-issue.jpg)
以及
![issue2](http://7xp8li.com1.z0.glb.clouddn.com/luffy-issue1.jpg)
对于图片以及pre标签的宽度设置

**Comment by hellflame** [comment]
chrome的这个开发工具内存泄露以及cpu占用存在明显bug.......

**Comment by kongxun** [comment]
@hellflame 文章的那个样式只是简单调了一下=-=确实还有bug

**Comment by idbord** [comment]
@hellflame 你是用pad看的吗？

**Comment by kongxun** [comment]
@hellflame  等我找到实习好好完善它=-=

**Comment by kongxun** [comment]
simply fixed
